import { useMemo, useState } from 'react';
import { Search, Shield, UserRound, UsersRound } from 'lucide-react';
import { getListUsersQueryKey, useListUsers } from '@workspace/api-client-react';
import { AppShell } from '@/components/app-shell';
import { useAuth } from '@/components/auth-context';

export function AdminUsersPage() {
  const { token, user } = useAuth(); const [search, setSearch] = useState('');
  const query = useListUsers({ query: { enabled: Boolean(token && user?.role === 'admin'), queryKey: getListUsersQueryKey() } });
  const users = useMemo(() => (query.data ?? []).filter((person) => `${person.name} ${person.email}`.toLowerCase().includes(search.toLowerCase())), [query.data, search]);
  if (user?.role !== 'admin') return <AppShell eyebrow="Restricted area" title="People"><div className="mx-auto max-w-xl rounded-[24px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-10 text-center"><div className="mx-auto mb-6 grid size-14 place-items-center rounded-2xl bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))]"><Shield size={25} /></div><h1 className="font-display text-4xl">This room is private.</h1><p className="mt-3 text-sm leading-6 text-[hsl(var(--muted-foreground))]">Administrator access is required to view people in this workspace.</p></div></AppShell>;
  return <AppShell eyebrow="Administration" title="People">
    <div className="mb-10 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-3 font-mono-ui text-[11px] uppercase tracking-[.18em] text-[hsl(var(--accent-foreground))]">Administration</p><h1 className="font-display text-5xl tracking-[-.05em]" data-testid="heading-admin-users">People, with context.</h1><p className="mt-4 max-w-lg text-sm leading-6 text-[hsl(var(--muted-foreground))]">A clear view of who has a key to this Harbor.</p></div><div className="flex items-center gap-2 rounded-full bg-[hsl(var(--primary))] px-4 py-2.5 text-xs font-bold text-[hsl(var(--primary-foreground))]"><UsersRound size={15} className="text-[hsl(var(--accent))]" /> {query.data?.length ?? 0} accounts</div></div>
    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-sm flex-1"><Search size={16} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[hsl(var(--muted-foreground))]" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name or email" className="h-11 w-full rounded-xl border border-[hsl(var(--input))] bg-[hsl(var(--card))] pl-10 pr-4 text-sm outline-none focus:border-[hsl(var(--accent-foreground))] focus:ring-4 focus:ring-[hsl(var(--accent)/.18)]" data-testid="input-search-users" /></div><p className="font-mono-ui text-[11px] uppercase tracking-[.14em] text-[hsl(var(--muted-foreground))]">{search ? `${users.length} matching` : 'All accounts'}</p></div>
    {query.isLoading ? <UsersSkeleton /> : query.isError ? <div className="rounded-2xl border border-[hsl(var(--destructive)/.25)] bg-[hsl(var(--destructive)/.06)] p-8"><h2 className="font-display text-3xl">People are out of reach.</h2><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">You may not have permission to view this list, or the service needs a moment.</p><button onClick={() => query.refetch()} className="mt-5 rounded-xl bg-[hsl(var(--primary))] px-4 py-2 text-sm font-bold text-[hsl(var(--primary-foreground))]" data-testid="button-retry-users">Try again</button></div> : users.length === 0 ? <EmptyUsers search={search} /> : <div className="overflow-hidden rounded-[22px] border border-[hsl(var(--border))] bg-[hsl(var(--card))]"><div className="hidden grid-cols-[1.4fr_1.4fr_.7fr_.7fr] gap-4 border-b border-[hsl(var(--border))] bg-[hsl(var(--muted)/.45)] px-6 py-3 font-mono-ui text-[10px] uppercase tracking-[.16em] text-[hsl(var(--muted-foreground))] sm:grid"><span>Person</span><span>Email</span><span>Role</span><span>Status</span></div><div className="divide-y divide-[hsl(var(--border))]">{users.map((person) => <UserRow key={person.id} person={person} />)}</div></div>}
  </AppShell>;
}

function UserRow({ person }: { person: { id: string; name: string; email: string; role: string; emailVerified: boolean; createdAt: string } }) {
  return <div className="grid gap-3 px-5 py-5 sm:grid-cols-[1.4fr_1.4fr_.7fr_.7fr] sm:items-center sm:gap-4 sm:px-6" data-testid={`row-user-${person.id}`}><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-[hsl(var(--accent)/.28)] text-xs font-extrabold text-[hsl(var(--accent-foreground))]">{person.name.slice(0, 1).toUpperCase()}</div><div><p className="font-bold" data-testid={`text-user-name-${person.id}`}>{person.name}</p><p className="text-xs text-[hsl(var(--muted-foreground))] sm:hidden">{person.email}</p></div></div><p className="hidden truncate text-sm text-[hsl(var(--muted-foreground))] sm:block" data-testid={`text-user-email-${person.id}`}>{person.email}</p><span className="w-fit rounded-full bg-[hsl(var(--muted))] px-2.5 py-1 font-mono-ui text-[10px] uppercase tracking-[.1em] text-[hsl(var(--muted-foreground))]">{person.role}</span><span className="flex items-center gap-1.5 text-xs font-semibold"><span className={`size-1.5 rounded-full ${person.emailVerified ? 'bg-[hsl(var(--accent-foreground))]' : 'bg-[hsl(var(--muted-foreground)/.4)]'}`} />{person.emailVerified ? 'Verified' : 'Pending'}</span></div>;
}
function UsersSkeleton() { return <div className="space-y-2" data-testid="loading-users">{[1, 2, 3, 4].map((row) => <div key={row} className="h-20 animate-pulse rounded-2xl bg-[hsl(var(--muted))]" />)}</div>; }
function EmptyUsers({ search }: { search: string }) { return <div className="rounded-[22px] border border-dashed border-[hsl(var(--border))] p-14 text-center" data-testid="empty-users"><div className="mx-auto mb-5 grid size-14 place-items-center rounded-2xl bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))]"><UserRound size={24} /></div><h2 className="font-display text-3xl">{search ? 'No one by that name.' : 'No accounts yet.'}</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-[hsl(var(--muted-foreground))]">{search ? 'Try a different name or email address.' : 'When people join this Harbor, they’ll appear here.'}</p></div>; }