import { ArrowUpRight, Check, Clock3, LockKeyhole, MailCheck, ShieldCheck } from 'lucide-react';
import type { ReactNode } from 'react';
import { Link } from 'wouter';
import { getGetCurrentUserQueryKey, useGetCurrentUser, useHealthCheck } from '@workspace/api-client-react';
import { AppShell } from '@/components/app-shell';
import { useAuth } from '@/components/auth-context';

export function DashboardPage() {
  const { token, user: sessionUser } = useAuth();
  const userQuery = useGetCurrentUser({ query: { enabled: Boolean(token), queryKey: getGetCurrentUserQueryKey() } });
  const healthQuery = useHealthCheck();
  const user = userQuery.data ?? sessionUser;
  if (userQuery.isLoading && !user) return <AppShell eyebrow="Your Harbor" title="Overview"><LoadingDashboard /></AppShell>;
  if (userQuery.isError && !user) return <AppShell eyebrow="Your Harbor" title="Overview"><ErrorPanel message="We couldn’t load your account details." onRetry={() => userQuery.refetch()} /></AppShell>;
  return <AppShell eyebrow="Your Harbor" title="Overview">
    <div className="mb-10 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 font-mono-ui text-[11px] uppercase tracking-[.18em] text-[hsl(var(--accent-foreground))]">Account overview</p><h1 className="font-display text-5xl tracking-[-.05em] sm:text-6xl" data-testid="heading-dashboard">Good to see you, {user?.name?.split(' ')[0] ?? 'there'}.</h1><p className="mt-4 max-w-lg text-sm leading-6 text-[hsl(var(--muted-foreground))]">A quiet view of the things that keep your account healthy.</p></div><div className="flex items-center gap-2 rounded-full border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-3 py-2 text-xs font-bold"><span className={`size-2 rounded-full ${healthQuery.isError ? 'bg-[hsl(var(--destructive))]' : 'bg-[hsl(var(--accent-foreground))]'}`} />{healthQuery.isError ? 'Service attention' : 'All systems steady'}</div></div>
    <div className="grid gap-5 md:grid-cols-[1.25fr_.75fr]"><section className="relative overflow-hidden rounded-[24px] bg-[hsl(var(--primary))] p-7 text-[hsl(var(--primary-foreground))] sm:p-9"><div className="absolute -right-14 -top-20 size-64 rounded-full border border-[hsl(var(--accent)/.2)]" /><div className="absolute -right-2 -top-7 size-36 rounded-full border border-[hsl(var(--accent)/.2)]" /><div className="relative"><div className="mb-12 flex items-center justify-between"><span className="font-mono-ui text-[10px] uppercase tracking-[.2em] text-[hsl(var(--accent))]">Harbor pass</span><LockKeyhole size={18} className="text-[hsl(var(--accent))]" /></div><p className="text-3xl font-extrabold tracking-[-.04em]" data-testid="text-dashboard-name">{user?.name}</p><p className="mt-1 text-sm text-[hsl(var(--primary-foreground)/.6)]" data-testid="text-dashboard-email">{user?.email}</p><div className="mt-10 flex flex-wrap gap-2"><span className="rounded-full bg-[hsl(var(--accent)/.15)] px-3 py-1.5 font-mono-ui text-[10px] uppercase tracking-[.12em] text-[hsl(var(--accent))]">{user?.role ?? 'user'} access</span><span className="rounded-full border border-[hsl(var(--primary-foreground)/.18)] px-3 py-1.5 font-mono-ui text-[10px] uppercase tracking-[.12em] text-[hsl(var(--primary-foreground)/.65)]">{user?.emailVerified ? 'email verified' : 'email pending'}</span></div></div></section><section className="rounded-[24px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-7 sm:p-9"><p className="font-mono-ui text-[10px] uppercase tracking-[.2em] text-[hsl(var(--muted-foreground))]">Account since</p><p className="mt-5 font-display text-4xl tracking-[-.04em]" data-testid="text-created-date">{user?.createdAt ? new Date(user.createdAt).toLocaleDateString(undefined, { month: 'short', year: 'numeric' }) : '—'}</p><p className="mt-2 text-sm leading-6 text-[hsl(var(--muted-foreground))]">Your Harbor account was created with care.</p><div className="mt-10 flex items-center gap-2 text-xs font-bold text-[hsl(var(--accent-foreground))]"><Clock3 size={15} /> Account history</div></section></div>
    <section className="mt-10"><div className="mb-5 flex items-end justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.2em] text-[hsl(var(--muted-foreground))]">Good foundations</p><h2 className="mt-2 text-xl font-extrabold tracking-[-.03em]">Your security checklist</h2></div><span className="font-mono-ui text-xs text-[hsl(var(--muted-foreground))]">02 / 02</span></div><div className="grid gap-3 sm:grid-cols-2"><ChecklistItem icon={<MailCheck />} title="Email address" detail={user?.emailVerified ? 'Verified and ready' : 'Verification needed'} complete={Boolean(user?.emailVerified)} href="/verify-email" /><ChecklistItem icon={<ShieldCheck />} title="Account access" detail="Password protected" complete href="/dashboard" /></div></section>
    <div className="mt-12 border-t border-[hsl(var(--border))] pt-6 text-xs text-[hsl(var(--muted-foreground))]">Need a hand? <Link href="/verify-email" className="font-bold text-[hsl(var(--foreground))] hover:text-[hsl(var(--accent-foreground))]" data-testid="link-dashboard-help">Visit account help <ArrowUpRight size={12} className="ml-1 inline" /></Link></div>
  </AppShell>;
}

function ChecklistItem({ icon, title, detail, complete, href }: { icon: ReactNode; title: string; detail: string; complete: boolean; href: string }) {
  return <Link href={href} className="group flex items-center gap-4 rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 hover:-translate-y-0.5 hover:border-[hsl(var(--accent-foreground)/.4)]" data-testid={`card-checklist-${title.toLowerCase().replace(' ', '-')}`}><div className={`grid size-11 shrink-0 place-items-center rounded-xl ${complete ? 'bg-[hsl(var(--accent)/.2)] text-[hsl(var(--accent-foreground))]' : 'bg-[hsl(var(--muted))] text-[hsl(var(--muted-foreground))]'}`}>{icon}</div><div className="min-w-0 flex-1"><p className="font-bold">{title}</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{detail}</p></div><Check size={17} className={complete ? 'text-[hsl(var(--accent-foreground))]' : 'text-[hsl(var(--muted-foreground)/.35)]'} /></Link>;
}

function LoadingDashboard() { return <div className="animate-pulse space-y-6"><div className="h-14 w-2/3 rounded-xl bg-[hsl(var(--muted))]" /><div className="h-64 rounded-[24px] bg-[hsl(var(--muted))]" /><div className="h-10 w-1/3 rounded-xl bg-[hsl(var(--muted))]" /></div>; }
function ErrorPanel({ message, onRetry }: { message: string; onRetry: () => void }) { return <div className="rounded-2xl border border-[hsl(var(--destructive)/.25)] bg-[hsl(var(--destructive)/.06)] p-8"><h2 className="font-display text-3xl">A small interruption</h2><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">{message}</p><button onClick={onRetry} className="mt-6 rounded-xl bg-[hsl(var(--primary))] px-4 py-2 text-sm font-bold text-[hsl(var(--primary-foreground))]" data-testid="button-retry-dashboard">Try again</button></div>; }