import { useState, type ReactNode } from 'react';
import { Compass, Heart, Bookmark, LogOut, Menu, Search, UserRound, Users, X, PenLine } from 'lucide-react';
import { Link, useLocation } from 'wouter';
import { useAuth } from '@/components/auth-context';
import { Brand } from '@/components/brand';

export function AppShell({ children, title, eyebrow }: { children: ReactNode; title: string; eyebrow: string }) {
  const { user, logout, isLoggingOut } = useAuth(); const [open, setOpen] = useState(false); const [location, setLocation] = useLocation();
  const signOut = async () => { try { await logout(); setLocation('/login'); } catch { /* keep the session visible when the server cannot end it */ } };
  const links = [
    { href: '/dashboard', label: 'For you', icon: Heart },
    { href: '/explore', label: 'Explore', icon: Compass },
    { href: '/search', label: 'Search', icon: Search },
    { href: '/bookmarks', label: 'Saved', icon: Bookmark },
  ];
  return <div className="min-h-[100dvh] bg-[hsl(var(--background))] text-[hsl(var(--foreground))]">
    {open && <button aria-label="Close navigation" className="fixed inset-0 z-30 bg-[hsl(var(--primary)/.35)] lg:hidden" onClick={() => setOpen(false)} data-testid="button-close-navigation" />}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[265px] -translate-x-full flex-col bg-[hsl(var(--sidebar))] p-6 text-[hsl(var(--sidebar-foreground))] transition-transform lg:translate-x-0 ${open ? 'translate-x-0' : ''}`}>
      <div className="flex items-center justify-between"><Brand inverse href="/dashboard" /><button className="p-2 text-[hsl(var(--sidebar-foreground)/.6)] lg:hidden" onClick={() => setOpen(false)} data-testid="button-close-sidebar"><X size={18} /></button></div>
       <div className="mt-16"><p className="mb-4 px-3 font-mono-ui text-[10px] uppercase tracking-[.2em] text-[hsl(var(--sidebar-foreground)/.45)]">The harbor</p><nav className="space-y-1">
         {links.map(({ href, label, icon: Icon }) => <Link key={href} href={href} onClick={() => setOpen(false)} className={`group flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition ${location === href ? 'bg-[hsl(var(--sidebar-accent))] font-bold text-[hsl(var(--sidebar-foreground))]' : 'text-[hsl(var(--sidebar-foreground)/.68)] hover:bg-[hsl(var(--sidebar-accent))] hover:text-[hsl(var(--sidebar-foreground))]'}`} data-testid={`link-${label.toLowerCase().replace(' ', '-')}`}><Icon size={17} className={location === href ? 'text-[hsl(var(--sidebar-primary))]' : ''} />{label}</Link>)}
         <Link href={user?.id ? `/profile/${user.id}` : '/dashboard'} onClick={() => setOpen(false)} className={`group flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold ${location.startsWith('/profile') ? 'bg-[hsl(var(--sidebar-accent))] text-[hsl(var(--sidebar-foreground))]' : 'text-[hsl(var(--sidebar-foreground)/.68)] hover:bg-[hsl(var(--sidebar-accent))]'}`}><UserRound size={17} /> Profile</Link>
         {user?.role === 'admin' && <Link href="/admin/users" onClick={() => setOpen(false)} className="group flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-[hsl(var(--sidebar-foreground)/.7)] hover:bg-[hsl(var(--sidebar-accent))]"><Users size={17} /> People</Link>}
       </nav></div>
       <div className="mt-auto space-y-5"><Link href="/dashboard" className="flex items-center gap-2 rounded-xl bg-[hsl(var(--sidebar-primary))] px-4 py-3 text-sm font-extrabold text-[hsl(var(--sidebar-primary-foreground))] hover:-translate-y-0.5"><PenLine size={16} /> Share a thought</Link><div className="rounded-2xl border border-[hsl(var(--sidebar-border))] bg-[hsl(var(--sidebar-accent)/.45)] p-4"><p className="font-display text-lg text-[hsl(var(--sidebar-foreground))]">A softer corner of the internet.</p><p className="mt-2 text-xs leading-5 text-[hsl(var(--sidebar-foreground)/.55)]">Make room for good things.</p></div><div className="flex items-center gap-3 border-t border-[hsl(var(--sidebar-border))] pt-5"><div className="grid size-9 shrink-0 place-items-center rounded-full bg-[hsl(var(--sidebar-primary))] text-xs font-extrabold text-[hsl(var(--sidebar-primary-foreground))]">{user?.name?.slice(0, 1).toUpperCase() ?? '?'}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold" data-testid="text-sidebar-user">{user?.name ?? 'Account holder'}</p><p className="truncate text-[11px] text-[hsl(var(--sidebar-foreground)/.5)]">{user?.email}</p></div><button onClick={signOut} disabled={isLoggingOut} className="p-2 text-[hsl(var(--sidebar-foreground)/.5)] hover:text-[hsl(var(--sidebar-primary))]" aria-label="Sign out" data-testid="button-sign-out"><LogOut size={16} /></button></div></div>
    </aside>
     <div className="social-canvas lg:pl-[265px]"><header className="sticky top-0 z-20 flex items-center justify-between border-b border-[hsl(var(--border)/.8)] bg-[hsl(var(--background)/.86)] px-5 py-4 backdrop-blur-md sm:px-8 lg:px-12"><button className="rounded-lg p-2 text-[hsl(var(--muted-foreground))] lg:hidden" onClick={() => setOpen(true)} data-testid="button-open-navigation"><Menu size={20} /></button><div className="ml-auto flex items-center gap-3 text-xs text-[hsl(var(--muted-foreground))]"><span className="hidden sm:inline">{title}</span><span className="size-1.5 rounded-full bg-[hsl(var(--accent-foreground))]" /><span className="font-semibold text-[hsl(var(--foreground))]" data-testid="text-header-user">{user?.name}</span></div></header><main className="mx-auto max-w-[1180px] px-5 py-8 sm:px-8 sm:py-10 lg:px-12">{children}</main></div>
  </div>;
}